runtime: python39
entrypoint: streamlit run lodge_cleaning_app.py
instance_class: F2
env_variables:
  STREAMLIT_SERVER_PORT: 8080
handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto
